version: '3.8'

services:
  web:
    build: ./django_test
    volumes:
      - ./django_test/:/usr/src/django_test/
    ports:
      - 8080:8080
    env_file:
      - ./.env
  db:
      image: postgres:15
      volumes:
        - postgres_data:/var/lib/postgresql/data/
      env_file:
        - ./.env        

volumes:
  postgres_data: